"use client";

import React, { useState, useId } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  ArrowRight,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  Download,
  ShieldCheck,
  Layers,
  HelpCircle,
  ChevronDown,
  Info,
  Maximize2,
  FileCode,
  CheckCircle2,
  AlertTriangle
} from "lucide-react";
import NextStepWorkflowLoop from "@/components/tools/NextStepWorkflowLoop";

type PaperType = "white" | "cream" | "color";
type CoverType = "paperback" | "hardcover";

interface TrimOption {
  name: string;
  width: number;
  height: number;
  popular?: boolean;
}

const TRIM_PRESETS: TrimOption[] = [
  { name: '8.5" x 11" (Workbook / Activity / Coloring)', width: 8.5, height: 11, popular: true },
  { name: '6" x 9" (Standard Trade Novel / Journal)', width: 6, height: 9, popular: true },
  { name: '5.5" x 8.5" (Compact Fiction / Memoir)', width: 5.5, height: 8.5 },
  { name: '5" x 8" (Pocket Fiction)', width: 5, height: 8 },
  { name: '8.25" x 6" (Landscape Children\'s Book)', width: 8.25, height: 6 },
  { name: '8.5" x 8.5" (Square Picture Book)', width: 8.5, height: 8.5 },
  { name: '7" x 10" (Textbook / Manual)', width: 7, height: 10 },
];

export default function KdpCoverCreatorClient() {
  const [trimIndex, setTrimIndex] = useState<number>(0);
  const [pageCount, setPageCount] = useState<number>(120);
  const [paperType, setPaperType] = useState<PaperType>("white");
  const [coverType, setCoverType] = useState<CoverType>("paperback");
  const [bookTitle, setBookTitle] = useState<string>("MY BESTSELLING BOOK");
  const [authorName, setAuthorName] = useState<string>("AUTHOR NAME");
  const [coverTheme, setCoverTheme] = useState<string>("navy");
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [hasDownloaded, setHasDownloaded] = useState<boolean>(false);

  // Copy feedback
  const [copiedWidth, setCopiedWidth] = useState(false);
  const [copiedHeight, setCopiedHeight] = useState(false);
  const [copiedSpine, setCopiedSpine] = useState(false);
  const [copiedAll, setCopiedAll] = useState(false);

  const selectedTrim = TRIM_PRESETS[trimIndex] ?? TRIM_PRESETS[0]!;

  // Multipliers (inches per page) based on official KDP specifications
  const getMultiplier = (type: PaperType): number => {
    switch (type) {
      case "white":
        return 0.002252;
      case "cream":
        return 0.0025;
      case "color":
        return 0.002347;
    }
  };

  const multiplier = getMultiplier(paperType);
  const spineWidthInches = Number((pageCount * multiplier).toFixed(4));

  // Calculations based on Cover Type
  // Paperback: 0.125" bleed on all outer edges
  // Hardcover (Case Laminate): 0.591" wrap + hinge allowance (KDP standard: board thickness + wrap)
  const isPaperback = coverType === "paperback";
  const bleed = isPaperback ? 0.125 : 0.591; // Bleed per edge
  const hinge = isPaperback ? 0 : 0.08; // Hardcover hinge area allowance

  const fullWidthInches = Number(((selectedTrim.width * 2) + spineWidthInches + (bleed * 2) + (hinge * 2)).toFixed(4));
  const fullHeightInches = Number((selectedTrim.height + (bleed * 2)).toFixed(4));

  // 300 DPI Pixel Dimensions
  const fullWidthPx = Math.round(fullWidthInches * 300);
  const fullHeightPx = Math.round(fullHeightInches * 300);
  const spineWidthPx = Math.round(spineWidthInches * 300);

  // Safe Margin Check
  const canHaveSpineText = pageCount >= 80;

  // Copy helpers
  const copyToClipboard = (text: string, setter: (val: boolean) => void) => {
    navigator.clipboard.writeText(text);
    setter(true);
    setTimeout(() => setter(false), 2000);
  };

  const copyAllSpecs = () => {
    const specs = [
      `--- Automated KDP Cover Creator Specifications ---`,
      `Cover Type: ${coverType.toUpperCase()}`,
      `Trim Size: ${selectedTrim.width}" x ${selectedTrim.height}"`,
      `Page Count: ${pageCount} pages (${paperType.toUpperCase()} paper)`,
      `Spine Width: ${spineWidthInches}" (${spineWidthPx} px @ 300 DPI)`,
      `Total Cover Width: ${fullWidthInches}" (${fullWidthPx} px @ 300 DPI)`,
      `Total Cover Height: ${fullHeightInches}" (${fullHeightPx} px @ 300 DPI)`,
      `Bleed: ${bleed}" on all outer edges`,
      `Safe Margin: Keep critical text 0.25" inside trim`,
      `Spine Text Permitted: ${canHaveSpineText ? "YES (>= 80 pages)" : "NO (< 80 pages)"}`,
      `Barcode Safe Zone: 2" wide x 1.2" high on bottom-right of back cover`,
      `Generated by KDPage Automated Cover Creator (https://kdpage.com/tools/kdp-cover-creator)`
    ].join("\n");
    copyToClipboard(specs, setCopiedAll);
  };

  // Download SVG Template
  const downloadSvgTemplate = () => {
    const svgContent = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${fullWidthPx} ${fullHeightPx}" width="${fullWidthPx}" height="${fullHeightPx}">
  <defs>
    <pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse">
      <path d="M 30 0 L 0 0 0 30" fill="none" stroke="#f1f5f9" stroke-width="1"/>
    </pattern>
  </defs>
  <!-- Background -->
  <rect width="100%" height="100%" fill="#ffffff" />
  <rect width="100%" height="100%" fill="url(#grid)" />

  <!-- Bleed Outer Boundary -->
  <rect x="0" y="0" width="${fullWidthPx}" height="${fullHeightPx}" fill="none" stroke="#ef4444" stroke-width="4" stroke-dasharray="8,8" />

  <!-- Back Cover Area -->
  <rect x="${Math.round(bleed * 300)}" y="${Math.round(bleed * 300)}" width="${Math.round(selectedTrim.width * 300)}" height="${Math.round(selectedTrim.height * 300)}" fill="#3b82f6" fill-opacity="0.05" stroke="#3b82f6" stroke-width="2" />
  <text x="${Math.round((bleed + selectedTrim.width / 2) * 300)}" y="${Math.round((fullHeightInches / 2) * 300)}" font-family="sans-serif" font-size="28" font-weight="bold" fill="#64748b" text-anchor="middle">BACK COVER</text>

  <!-- Spine Area -->
  <rect x="${Math.round((bleed + selectedTrim.width) * 300)}" y="${Math.round(bleed * 300)}" width="${spineWidthPx}" height="${Math.round(selectedTrim.height * 300)}" fill="#f59e0b" fill-opacity="0.15" stroke="#f59e0b" stroke-width="2" />
  <text x="${Math.round((bleed + selectedTrim.width + spineWidthInches / 2) * 300)}" y="${Math.round((fullHeightInches / 2) * 300)}" font-family="sans-serif" font-size="20" font-weight="bold" fill="#b45309" text-anchor="middle" transform="rotate(-90 ${Math.round((bleed + selectedTrim.width + spineWidthInches / 2) * 300)} ${Math.round((fullHeightInches / 2) * 300)})">SPINE: ${spineWidthInches}"</text>

  <!-- Front Cover Area -->
  <rect x="${Math.round((bleed + selectedTrim.width + spineWidthInches) * 300)}" y="${Math.round(bleed * 300)}" width="${Math.round(selectedTrim.width * 300)}" height="${Math.round(selectedTrim.height * 300)}" fill="#10b981" fill-opacity="0.05" stroke="#10b981" stroke-width="2" />
  <text x="${Math.round((bleed + selectedTrim.width * 1.5 + spineWidthInches) * 300)}" y="${Math.round((fullHeightInches / 2) * 300)}" font-family="sans-serif" font-size="28" font-weight="bold" fill="#059669" text-anchor="middle">FRONT COVER</text>

  <!-- Barcode Zone (2" x 1.2" bottom right of back cover) -->
  <rect x="${Math.round((bleed + selectedTrim.width - 2.25) * 300)}" y="${Math.round((bleed + selectedTrim.height - 1.45) * 300)}" width="600" height="360" fill="#f8fafc" stroke="#94a3b8" stroke-width="2" stroke-dasharray="6,6" />
  <text x="${Math.round((bleed + selectedTrim.width - 1.25) * 300)}" y="${Math.round((bleed + selectedTrim.height - 0.85) * 300)}" font-family="sans-serif" font-size="16" fill="#64748b" text-anchor="middle">BARCODE ZONE (Keep Clear)</text>

  <!-- Specs Header -->
  <text x="${Math.round(fullWidthPx / 2)}" y="50" font-family="sans-serif" font-size="22" font-weight="bold" fill="#0f172a" text-anchor="middle">Automated KDP Cover Template: ${selectedTrim.name} • ${pageCount} Pages (${paperType.toUpperCase()})</text>
  <text x="${Math.round(fullWidthPx / 2)}" y="85" font-family="sans-serif" font-size="16" fill="#64748b" text-anchor="middle">Total Dimensions: ${fullWidthInches}" x ${fullHeightInches}" (${fullWidthPx} x ${fullHeightPx} px @ 300 DPI)</text>
</svg>`;

    const blob = new Blob([svgContent], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `kdp-cover-template-${selectedTrim.width}x${selectedTrim.height}-${pageCount}pages.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setHasDownloaded(true);
  };

  // Color theme palettes for live preview
  const getThemeColors = () => {
    switch (coverTheme) {
      case "navy":
        return { bg: "#0f172a", spine: "#1e293b", text: "#f8fafc", accent: "#38bdf8" };
      case "gold":
        return { bg: "#1c1917", spine: "#292524", text: "#fef08a", accent: "#eab308" };
      case "emerald":
        return { bg: "#064e3b", spine: "#065f46", text: "#ecfdf5", accent: "#34d399" };
      case "crimson":
        return { bg: "#881337", spine: "#9f1239", text: "#ffe4e6", accent: "#fb7185" };
      default:
        return { bg: "#0f172a", spine: "#1e293b", text: "#f8fafc", accent: "#38bdf8" };
    }
  };

  const theme = getThemeColors();

  const faqs = [
    {
      q: "What is an Automated KDP Cover Creator?",
      a: "An Automated KDP Cover Creator is a specialized software tool that automatically calculates the exact full wrap-around cover dimensions (front cover, back cover, spine width, and bleed margins) for Amazon Kindle Direct Publishing (KDP). It eliminates manual math mistakes and guarantees zero Amazon print rejection."
    },
    {
      q: "How does the automated spine width calculation work?",
      a: "Amazon KDP calculates spine thickness based on paper type and page count. For standard White paper, each page adds 0.002252 inches (Page Count × 0.002252). For Cream paper, each page is 0.0025 inches. For Color paper, each page is 0.002347 inches. Our automated creator performs this math in real-time as you adjust your page count."
    },
    {
      q: "Can I print text on my book spine?",
      a: "Amazon KDP requires books to have at least 80 pages before you are permitted to place text on the spine. If your book is 79 pages or fewer, Amazon's print guidelines require the spine to remain blank to prevent text from shifting onto the front or back cover during print trimming."
    },
    {
      q: "What bleed margin does Amazon KDP require for covers?",
      a: "Paperback covers require exactly 0.125 inches (1/8 inch or 3.2 mm) of bleed added to all four outer edges (top, bottom, left, and right). This prevents white unprinted borders after mechanical cutting. Hardcovers require 0.591 inches to account for wrapping around the physical binder boards."
    },
    {
      q: "Where is the Amazon KDP barcode placed on the cover?",
      a: "Amazon automatically stamps a 2-inch wide by 1.2-inch high (50.8 mm × 30.5 mm) barcode on the lower-right corner of the back cover. You must keep this area completely free of important text, logos, or crucial artwork."
    },
    {
      q: "Can I take these automated dimensions directly into the KDPage Cover Studio?",
      a: "Yes! Click the 'Launch Full Cover Studio' button on this page to load these exact calculated dimensions, page count, and spine width directly into KDPage's Fabric.js canvas editor, where you can add layers, images, custom typography, and export print-ready 300 DPI vector PDFs."
    }
  ];

  const trimParam = `${selectedTrim.width}x${selectedTrim.height}`;
  const studioHref = `/studio?tab=cover&trim=${encodeURIComponent(trimParam)}&pages=${pageCount}&paper=${paperType}`;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 selection:bg-indigo-500 selection:text-white pb-24">
      {/* ── Breadcrumbs & Header ── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 pt-8 pb-4">
        <div className="flex items-center gap-2 text-xs font-semibold text-slate-400 mb-6">
          <Link href="/" className="hover:text-white transition">Home</Link>
          <span>/</span>
          <Link href="/tools" className="hover:text-white transition">Free Tools</Link>
          <span>/</span>
          <span className="text-indigo-400">Automated KDP Cover Creator</span>
        </div>

        <div className="text-center max-w-4xl mx-auto space-y-4">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-black uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            100% Free Official Amazon KDP Utility (2026)
          </div>

          <h1 className="text-3xl sm:text-5xl md:text-6xl font-black tracking-tight text-white leading-tight">
            Automated <span className="bg-gradient-to-r from-amber-400 via-yellow-300 to-amber-500 bg-clip-text text-transparent">KDP Cover Creator</span>
          </h1>

          <p className="text-slate-300 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
            Generate pixel-perfect, print-ready Amazon KDP wrap-around book covers automatically. Real-time spine thickness math, bleed margin safety, and 300 DPI export.
          </p>
        </div>
      </div>

      {/* ── Main Interactive Generator Studio ── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 mt-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Automation Controls & Inputs */}
          <div className="lg:col-span-5 bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-4">
              <h2 className="text-lg font-black text-white flex items-center gap-2">
                <Layers className="w-5 h-5 text-indigo-400" />
                Book &amp; Trim Settings
              </h2>
              <span className="text-[11px] font-bold text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/20">
                Auto-Calibrating
              </span>
            </div>

            {/* Cover Type: Paperback vs Hardcover */}
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-400 mb-2">
                1. Cover Type
              </label>
              <div className="grid grid-cols-2 gap-3">
                <button
                  type="button"
                  onClick={() => setCoverType("paperback")}
                  className={`py-3 px-4 rounded-xl font-black text-xs transition flex items-center justify-center gap-2 cursor-pointer border ${
                    isPaperback
                      ? "bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-600/30"
                      : "bg-slate-800/80 border-slate-700 text-slate-300 hover:bg-slate-800"
                  }`}
                >
                  <span>Paperback</span>
                  <span className="text-[9px] opacity-75">(0.125" Bleed)</span>
                </button>
                <button
                  type="button"
                  onClick={() => setCoverType("hardcover")}
                  className={`py-3 px-4 rounded-xl font-black text-xs transition flex items-center justify-center gap-2 cursor-pointer border ${
                    !isPaperback
                      ? "bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-600/30"
                      : "bg-slate-800/80 border-slate-700 text-slate-300 hover:bg-slate-800"
                  }`}
                >
                  <span>Hardcover</span>
                  <span className="text-[9px] opacity-75">(Case Wrap)</span>
                </button>
              </div>
            </div>

            {/* Trim Size Presets */}
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-400 mb-2">
                2. Trim Size
              </label>
              <select
                value={trimIndex}
                onChange={(e) => setTrimIndex(Number(e.target.value))}
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-sm font-bold text-white focus:outline-none focus:border-indigo-500"
              >
                {TRIM_PRESETS.map((preset, idx) => (
                  <option key={preset.name} value={idx}>
                    {preset.name}
                  </option>
                ))}
              </select>
            </div>

            {/* Paper Color & Thickness */}
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-400 mb-2">
                3. Paper Stock (Thickness Formula)
              </label>
              <div className="grid grid-cols-3 gap-2">
                <button
                  type="button"
                  onClick={() => setPaperType("white")}
                  className={`py-2.5 px-3 rounded-xl text-xs font-bold transition border ${
                    paperType === "white"
                      ? "bg-amber-400 border-amber-300 text-black font-black"
                      : "bg-slate-950 border-slate-800 text-slate-300 hover:border-slate-700"
                  }`}
                >
                  White Paper
                  <span className="block text-[9px] opacity-80">0.002252"</span>
                </button>
                <button
                  type="button"
                  onClick={() => setPaperType("cream")}
                  className={`py-2.5 px-3 rounded-xl text-xs font-bold transition border ${
                    paperType === "cream"
                      ? "bg-amber-400 border-amber-300 text-black font-black"
                      : "bg-slate-950 border-slate-800 text-slate-300 hover:border-slate-700"
                  }`}
                >
                  Cream Paper
                  <span className="block text-[9px] opacity-80">0.002500"</span>
                </button>
                <button
                  type="button"
                  onClick={() => setPaperType("color")}
                  className={`py-2.5 px-3 rounded-xl text-xs font-bold transition border ${
                    paperType === "color"
                      ? "bg-amber-400 border-amber-300 text-black font-black"
                      : "bg-slate-950 border-slate-800 text-slate-300 hover:border-slate-700"
                  }`}
                >
                  Color Interior
                  <span className="block text-[9px] opacity-80">0.002347"</span>
                </button>
              </div>
            </div>

            {/* Page Count Slider */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-black uppercase tracking-wider text-slate-400">
                  4. Exact Page Count
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="number"
                    min={24}
                    max={828}
                    value={pageCount}
                    onChange={(e) => setPageCount(Math.max(24, Math.min(828, Number(e.target.value) || 24)))}
                    className="w-20 bg-slate-950 border border-slate-700 rounded-lg px-2.5 py-1 text-center font-black text-amber-400 text-sm focus:outline-none focus:border-amber-400"
                  />
                  <span className="text-xs text-slate-400">pages</span>
                </div>
              </div>
              <input
                type="range"
                min={24}
                max={828}
                value={pageCount}
                onChange={(e) => setPageCount(Number(e.target.value))}
                className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-amber-400"
              />
              <div className="flex justify-between text-[10px] text-slate-500 font-bold mt-1">
                <span>24 pages (Min)</span>
                <span>Spine text allowed: {canHaveSpineText ? "✓ (≥ 80)" : "✗ (< 80)"}</span>
                <span>828 pages (Max)</span>
              </div>
            </div>

            {/* Live Text Customization */}
            <div className="space-y-3 pt-2 border-t border-slate-800">
              <label className="block text-xs font-black uppercase tracking-wider text-slate-400">
                5. Cover Typography Preview
              </label>
              <input
                type="text"
                value={bookTitle}
                onChange={(e) => setBookTitle(e.target.value)}
                placeholder="Book Title"
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs font-bold text-white focus:outline-none focus:border-indigo-500"
              />
              <input
                type="text"
                value={authorName}
                onChange={(e) => setAuthorName(e.target.value)}
                placeholder="Author Name"
                className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs font-bold text-white focus:outline-none focus:border-indigo-500"
              />
            </div>

            {/* Theme Presets */}
            <div>
              <label className="block text-xs font-black uppercase tracking-wider text-slate-400 mb-2">
                6. Palette Theme
              </label>
              <div className="flex items-center gap-2">
                {[
                  { id: "navy", name: "Navy", color: "#0f172a" },
                  { id: "gold", name: "Midnight Gold", color: "#1c1917" },
                  { id: "emerald", name: "Emerald", color: "#064e3b" },
                  { id: "crimson", name: "Crimson", color: "#881337" },
                ].map((t) => (
                  <button
                    key={t.id}
                    type="button"
                    onClick={() => setCoverTheme(t.id)}
                    className={`flex-1 py-2 rounded-xl text-[11px] font-bold border transition ${
                      coverTheme === t.id
                        ? "border-amber-400 text-white shadow-md"
                        : "border-slate-800 text-slate-400 hover:border-slate-700"
                    }`}
                    style={{ backgroundColor: t.color }}
                  >
                    {t.name}
                  </button>
                ))}
              </div>
            </div>

          </div>

          {/* Right Column: Live Automated Canvas & Precision Output */}
          <div className="lg:col-span-7 space-y-6">

            {/* Precision Dimension Badges */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 text-center relative group">
                <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-1">
                  Full Cover Width
                </span>
                <div className="text-xl sm:text-2xl font-black text-amber-400">
                  {fullWidthInches}"
                </div>
                <div className="text-[10px] text-slate-400 font-semibold mt-1">
                  {fullWidthPx} px @ 300 DPI
                </div>
                <button
                  type="button"
                  onClick={() => copyToClipboard(fullWidthInches.toString(), setCopiedWidth)}
                  className="mt-2 text-[10px] font-bold text-slate-300 hover:text-white flex items-center justify-center gap-1 mx-auto"
                >
                  {copiedWidth ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copiedWidth ? "Copied!" : "Copy"}
                </button>
              </div>

              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 text-center relative group">
                <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-1">
                  Full Cover Height
                </span>
                <div className="text-xl sm:text-2xl font-black text-amber-400">
                  {fullHeightInches}"
                </div>
                <div className="text-[10px] text-slate-400 font-semibold mt-1">
                  {fullHeightPx} px @ 300 DPI
                </div>
                <button
                  type="button"
                  onClick={() => copyToClipboard(fullHeightInches.toString(), setCopiedHeight)}
                  className="mt-2 text-[10px] font-bold text-slate-300 hover:text-white flex items-center justify-center gap-1 mx-auto"
                >
                  {copiedHeight ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copiedHeight ? "Copied!" : "Copy"}
                </button>
              </div>

              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-4 text-center relative group">
                <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-1">
                  Spine Thickness
                </span>
                <div className="text-xl sm:text-2xl font-black text-emerald-400">
                  {spineWidthInches}"
                </div>
                <div className="text-[10px] text-slate-400 font-semibold mt-1">
                  {spineWidthPx} px @ 300 DPI
                </div>
                <button
                  type="button"
                  onClick={() => copyToClipboard(spineWidthInches.toString(), setCopiedSpine)}
                  className="mt-2 text-[10px] font-bold text-slate-300 hover:text-white flex items-center justify-center gap-1 mx-auto"
                >
                  {copiedSpine ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  {copiedSpine ? "Copied!" : "Copy"}
                </button>
              </div>
            </div>

            {/* Live Visual Canvas Preview */}
            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl relative overflow-hidden">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
                  <span className="text-xs font-black text-slate-300 uppercase tracking-wider">
                    Live Wrap-Around Blueprint
                  </span>
                </div>
                <div className="flex items-center gap-3 text-[11px] font-semibold text-slate-400">
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-red-500" /> Bleed 0.125"
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-amber-400" /> Spine
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-slate-400" /> Barcode
                  </span>
                </div>
              </div>

              {/* Scaled Visual Wrap-Around Simulation */}
              <div 
                className="w-full aspect-[16/10] rounded-2xl border-2 border-dashed border-red-500/60 p-2.5 flex items-stretch relative transition-colors duration-300 shadow-inner"
                style={{ backgroundColor: theme.bg }}
              >
                {/* Back Cover */}
                <div className="flex-1 flex flex-col justify-between p-4 border-r border-slate-700/50 relative">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 block mb-1">
                      Back Cover
                    </span>
                    <p className="text-[9px] text-slate-400 font-medium leading-relaxed max-w-[140px] line-clamp-3">
                      Automated full-wrap layout. Blurb text, feature bullets, and graphics sit comfortably inside safe margins.
                    </p>
                  </div>

                  {/* Barcode Protected Zone */}
                  <div className="self-end bg-slate-950/80 border border-dashed border-slate-500 text-slate-400 text-[8px] font-black uppercase p-2 rounded flex flex-col items-center justify-center text-center w-28 h-16 shadow-md">
                    <span>Barcode Zone</span>
                    <span className="text-[7px] text-slate-500">2" × 1.2" (Keep Clear)</span>
                  </div>
                </div>

                {/* Spine */}
                <div 
                  className="flex flex-col items-center justify-center border-x-2 border-amber-400/80 px-1 relative transition-all duration-300"
                  style={{ 
                    backgroundColor: theme.spine, 
                    width: `${Math.max(28, Math.min(80, spineWidthInches * 70))}px` 
                  }}
                >
                  {canHaveSpineText ? (
                    <span 
                      className="text-[9px] font-black uppercase tracking-wider text-amber-300 whitespace-nowrap transform -rotate-90 select-none"
                    >
                      {bookTitle.slice(0, 24)}
                    </span>
                  ) : (
                    <span className="text-[7px] text-amber-400/60 font-bold uppercase tracking-widest transform -rotate-90 whitespace-nowrap">
                      No Spine Text (&lt;80p)
                    </span>
                  )}
                </div>

                {/* Front Cover */}
                <div className="flex-1 flex flex-col justify-between p-4 relative text-right">
                  <div>
                    <span className="text-[10px] font-black uppercase tracking-widest text-emerald-400 block mb-1">
                      Front Cover
                    </span>
                  </div>

                  <div className="text-center my-auto px-2">
                    <h3 
                      className="font-black text-sm sm:text-base md:text-lg tracking-tight uppercase leading-snug line-clamp-2"
                      style={{ color: theme.text }}
                    >
                      {bookTitle || "YOUR BOOK TITLE"}
                    </h3>
                    <div 
                      className="w-8 h-0.5 mx-auto my-2 rounded-full"
                      style={{ backgroundColor: theme.accent }}
                    />
                    <p className="text-[10px] font-bold text-slate-300 uppercase tracking-widest">
                      {authorName || "AUTHOR NAME"}
                    </p>
                  </div>

                  <div className="text-right">
                    <span className="text-[8px] font-semibold text-slate-400">
                      Trim: {selectedTrim.width}" × {selectedTrim.height}"
                    </span>
                  </div>
                </div>
              </div>

              {/* Safety Warning if page count < 80 */}
              {!canHaveSpineText && (
                <div className="mt-4 p-3 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-center gap-3 text-amber-300 text-xs font-semibold">
                  <AlertTriangle className="w-4 h-4 shrink-0 text-amber-400" />
                  <span>
                    <strong>Spine Notice:</strong> At {pageCount} pages, spine width is {spineWidthInches}". Amazon KDP requires <strong>80+ pages</strong> to print spine text. Keep spine clear of text.
                  </span>
                </div>
              )}
            </div>

            {/* Action Buttons: Studio Launch & Download */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Link
                href={studioHref}
                className="w-full py-4.5 px-6 rounded-2xl bg-gradient-to-r from-amber-400 via-yellow-400 to-amber-500 hover:from-amber-300 hover:to-yellow-400 text-slate-950 font-black text-sm uppercase tracking-wider flex items-center justify-center gap-2 shadow-xl shadow-amber-500/20 hover:scale-[1.02] active:scale-95 transition-all text-center"
              >
                <span>Launch Full Cover Studio →</span>
                <Sparkles className="w-4 h-4 text-black" />
              </Link>

              <button
                type="button"
                onClick={downloadSvgTemplate}
                className="w-full py-4.5 px-6 rounded-2xl bg-slate-900 hover:bg-slate-800 border border-slate-700 text-white font-black text-sm uppercase tracking-wider flex items-center justify-center gap-2 transition hover:scale-[1.02] active:scale-95 cursor-pointer shadow-lg"
              >
                <Download className="w-4 h-4 text-amber-400" />
                <span>Download SVG Template</span>
              </button>
            </div>

            {/* Copy Full Specs Button */}
            <button
              type="button"
              onClick={copyAllSpecs}
              className="w-full py-3 rounded-xl bg-slate-950 hover:bg-slate-900 border border-slate-800 text-slate-400 hover:text-white text-xs font-bold transition flex items-center justify-center gap-2 cursor-pointer"
            >
              {copiedAll ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedAll ? "All Specifications Copied to Clipboard!" : "Copy Full KDP Specifications for Photoshop / InDesign / Illustrator"}
            </button>

          </div>

        </div>
      </div>

      {/* ── Contextual Next Step Publishing Loop ── */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 mt-10">
        <NextStepWorkflowLoop
          category="cover"
          justDownloaded={hasDownloaded}
          onDismissCelebration={() => setHasDownloaded(false)}
        />
      </div>

      {/* ── Deep Educational & SEO Authority Section ── */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 mt-24 space-y-16">
        
        {/* Section 1: Why Automated Cover Creation Matters */}
        <section className="bg-slate-900/60 border border-slate-800/80 rounded-3xl p-8 sm:p-12 space-y-6">
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            Why Amazon Self-Publishers Need an Automated KDP Cover Creator
          </h2>
          <p className="text-slate-300 text-base leading-relaxed">
            Designing a book cover for Amazon KDP is notoriously unforgiving. Unlike standard web graphics or simple front-cover eBook art, print-on-demand paperback and hardcover books require an exact, single-sheet <strong>wrap-around cover PDF</strong>. This single document must simultaneously house the back cover, spine thickness, and front cover—wrapped in a mandatory <strong>0.125" (3.2 mm) outer bleed</strong>.
          </p>
          <p className="text-slate-300 text-base leading-relaxed">
            If your spine width calculation is off by even 0.02 inches, mechanical cutting shifts occur, causing your title to bleed over the spine fold or triggering Amazon's automated print rejection bot: <em>"Your cover file does not match the page count of your interior."</em> An automated KDP cover creator eliminates human calculation error by pulling live formulas directly from Amazon's official print guidelines.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
            <div className="bg-slate-950/80 p-5 rounded-2xl border border-slate-800 space-y-2">
              <ShieldCheck className="w-6 h-6 text-emerald-400" />
              <h3 className="text-white font-bold text-sm">Zero Margin Rejections</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Calculates precise 0.125" outer bleeds and 0.25" internal safety margins automatically.
              </p>
            </div>
            <div className="bg-slate-950/80 p-5 rounded-2xl border border-slate-800 space-y-2">
              <Layers className="w-6 h-6 text-amber-400" />
              <h3 className="text-white font-bold text-sm">Official KDP Paper Math</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Uses official White (0.002252"), Cream (0.0025"), and Color (0.002347") paper thickness constants.
              </p>
            </div>
            <div className="bg-slate-950/80 p-5 rounded-2xl border border-slate-800 space-y-2">
              <FileCode className="w-6 h-6 text-sky-400" />
              <h3 className="text-white font-bold text-sm">300 DPI Print Export</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Converts inches directly to pixel dimensions so your graphics never render blurry or pixelated.
              </p>
            </div>
          </div>
        </section>

        {/* Section 2: Mathematical Breakdown */}
        <section className="space-y-6">
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            How Automated KDP Cover Calculation Works (The Exact Formulas)
          </h2>
          <p className="text-slate-300 text-base leading-relaxed">
            Amazon KDP requires specific geometric formulas depending on whether you are publishing a paperback or a hardcover case-laminate book:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-3">
              <h3 className="text-lg font-black text-amber-400">Paperback Cover Formula</h3>
              <ul className="text-xs text-slate-300 space-y-2 font-mono">
                <li>• Spine Width = Page Count × Paper Thickness</li>
                <li>• Total Width = Bleed (0.125") + Back Cover Width + Spine Width + Front Cover Width + Bleed (0.125")</li>
                <li>• Total Height = Bleed (0.125") + Trim Height + Bleed (0.125")</li>
                <li>• Total Height = Trim Height + 0.25"</li>
              </ul>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-3">
              <h3 className="text-lg font-black text-indigo-400">Hardcover (Case Laminate) Formula</h3>
              <ul className="text-xs text-slate-300 space-y-2 font-mono">
                <li>• Spine Width = Page Count × Paper Thickness</li>
                <li>• Wrap Allowance = 0.591" on all 4 outer edges</li>
                <li>• Hinge Allowance = 0.08" on both sides of spine</li>
                <li>• Total Width = (Trim Width × 2) + Spine + (0.591" × 2) + 0.16"</li>
                <li>• Total Height = Trim Height + (0.591" × 2)</li>
              </ul>
            </div>
          </div>
        </section>

        {/* Section 3: Feature Comparison Table */}
        <section className="space-y-6">
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            Automated KDP Cover Creator vs. Canva vs. Amazon Cover Creator
          </h2>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse border border-slate-800 rounded-2xl overflow-hidden text-xs sm:text-sm">
              <thead>
                <tr className="bg-slate-900 text-slate-300">
                  <th className="p-4 border-b border-slate-800 font-black">Feature</th>
                  <th className="p-4 border-b border-slate-800 font-black text-amber-400">KDPage Automated Cover Creator</th>
                  <th className="p-4 border-b border-slate-800 font-black">Amazon KDP Built-in Creator</th>
                  <th className="p-4 border-b border-slate-800 font-black">Canva</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800 text-slate-300">
                <tr>
                  <td className="p-4 font-bold text-white">Live Spine Thickness Calculation</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ 100% Automated</td>
                  <td className="p-4 text-amber-400">✓ Automated (Basic)</td>
                  <td className="p-4 text-rose-400">✗ Manual Math Required</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold text-white">Barcode Area Protection</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Visual 2"x1.2" Safe Zone</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Handled</td>
                  <td className="p-4 text-rose-400">✗ No Barcode Guide</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold text-white">300 DPI Vector PDF Export</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Print-Ready Included</td>
                  <td className="p-4 text-amber-400">Restricted Templates</td>
                  <td className="p-4 text-amber-400">Requires Canva Pro ($120/yr)</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold text-white">Hardcover &amp; Paperback Modes</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Both Supported</td>
                  <td className="p-4 text-amber-400">Limited options</td>
                  <td className="p-4 text-rose-400">✗ Manual Board Wrap Math</td>
                </tr>
                <tr>
                  <td className="p-4 font-bold text-white">Zero Installation Cloud Suite</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Runs in Browser</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Runs in Browser</td>
                  <td className="p-4 text-emerald-400 font-bold">✓ Runs in Browser</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* Section 4: Step-by-Step Guide */}
        <section className="bg-slate-900/60 border border-slate-800 rounded-3xl p-8 sm:p-12 space-y-6">
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
            How to Create an Automated KDP Cover in 3 Simple Steps
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="space-y-3">
              <div className="w-10 h-10 rounded-xl bg-amber-400/10 text-amber-400 border border-amber-400/20 font-black text-lg flex items-center justify-center">
                1
              </div>
              <h3 className="text-white font-bold text-base">Select Trim &amp; Page Count</h3>
              <p className="text-slate-400 text-xs leading-relaxed">
                Choose your book format (e.g. 8.5" x 11" for coloring/puzzle books or 6" x 9" for novels), paper type, and exact interior page count.
              </p>
            </div>

            <div className="space-y-3">
              <div className="w-10 h-10 rounded-xl bg-indigo-400/10 text-indigo-400 border border-indigo-400/20 font-black text-lg flex items-center justify-center">
                2
              </div>
              <h3 className="text-white font-bold text-base">Auto-Generate Dimensions</h3>
              <p className="text-slate-400 text-xs leading-relaxed">
                The engine immediately renders your exact full wrap-around dimensions, spine width, and safe margin guides with 0.125" bleed.
              </p>
            </div>

            <div className="space-y-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-400/10 text-emerald-400 border border-emerald-400/20 font-black text-lg flex items-center justify-center">
                3
              </div>
              <h3 className="text-white font-bold text-base">Launch Studio or Export</h3>
              <p className="text-slate-400 text-xs leading-relaxed">
                Open directly in KDPage Fabric Cover Studio to style your cover visually, or download the SVG template to edit in Photoshop/Illustrator.
              </p>
            </div>
          </div>
        </section>

        {/* Section 5: FAQ Accordion */}
        <section className="space-y-6">
          <div className="text-center space-y-2">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
              Frequently Asked Questions About Automated KDP Covers
            </h2>
            <p className="text-slate-400 text-sm">
              Everything you need to know about Amazon KDP cover specifications and compliance.
            </p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, idx) => (
              <div 
                key={faq.q}
                className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden transition"
              >
                <button
                  type="button"
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full p-5 text-left font-black text-sm sm:text-base text-white flex items-center justify-between gap-4 cursor-pointer hover:text-amber-400 transition"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 shrink-0 transition-transform ${openFaq === idx ? "rotate-180 text-amber-400" : "text-slate-400"}`} />
                </button>
                {openFaq === idx && (
                  <div className="px-5 pb-5 text-xs sm:text-sm text-slate-300 font-medium leading-relaxed border-t border-slate-800/60 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Section 6: Bottom Call to Action */}
        <section className="bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 border border-indigo-500/30 rounded-3xl p-8 sm:p-12 text-center space-y-6 relative overflow-hidden shadow-2xl">
          <div className="max-w-2xl mx-auto space-y-4">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-400/10 border border-amber-400/20 text-amber-400 text-xs font-black uppercase tracking-wider">
              🚀 Ready to Publish Your Amazon KDP Book?
            </span>
            <h2 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
              Create Your Complete Book in 5 Minutes
            </h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              Combine your automated wrap-around cover with KDPage’s algorithmic puzzle engines: Word Search, Sudoku, Mazes, and lined journals. Export 300 DPI vector PDFs ready for immediate Amazon KDP upload.
            </p>
            <div className="pt-2 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href="/studio"
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-amber-400 hover:bg-amber-300 text-slate-950 font-black text-sm uppercase tracking-wider transition shadow-lg shadow-amber-400/20 flex items-center justify-center gap-2"
              >
                <span>Launch KDPage Studio Free</span>
                <ArrowRight className="w-4 h-4 text-black" />
              </Link>
              <Link
                href="/tools/kdp-puzzle-generator"
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-slate-800 hover:bg-slate-700 text-amber-400 font-bold text-sm transition flex items-center justify-center gap-2 border border-slate-700 hover:border-amber-400/50"
              >
                Free KDP Puzzle Generator →
              </Link>
              <Link
                href="/tools"
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-slate-900/80 hover:bg-slate-800 text-slate-300 font-semibold text-sm transition flex items-center justify-center gap-2 border border-slate-800"
              >
                Explore 30+ Free KDP Tools
              </Link>
            </div>
          </div>
        </section>

      </div>
    </div>
  );
}
