// Curated collection of famous, inspiring quotes for Cryptogram KDP Puzzle Books.
// All uppercase, clean punctuation, family-friendly, and formatted for optimal cryptographic puzzle solving.

export const CRYPTOGRAM_QUOTES: string[] = [
  "THE ONLY LIMIT TO OUR REALIZATION OF TOMORROW WILL BE OUR DOUBTS OF TODAY.",
  "SUCCESS IS NOT FINAL, FAILURE IS NOT FATAL: IT IS THE COURAGE TO CONTINUE THAT COUNTS.",
  "BE THE CHANGE THAT YOU WISH TO SEE IN THE WORLD.",
  "IN THE MIDDLE OF DIFFICULTY LIES OPPORTUNITY.",
  "IMAGINATION IS MORE IMPORTANT THAN KNOWLEDGE. KNOWLEDGE IS LIMITED. IMAGINATION ENCIRCLES THE WORLD.",
  "DO NOT GO WHERE THE PATH MAY LEAD, GO INSTEAD WHERE THERE IS NO PATH AND LEAVE A TRAIL.",
  "THE FUTURE BELONGS TO THOSE WHO BELIEVE IN THE BEAUTY OF THEIR DREAMS.",
  "WHAT LIES BEHIND US AND WHAT LIES BEFORE US ARE TINY MATTERS COMPARED TO WHAT LIES WITHIN US.",
  "IT IS DURING OUR DARKEST MOMENTS THAT WE MUST FOCUS TO SEE THE LIGHT.",
  "DO NOT WATCH THE CLOCK; DO WHAT IT DOES. KEEP GOING.",
  "YOU DEFINE YOUR OWN LIFE. DON'T LET OTHER PEOPLE WRITE YOUR SCRIPT.",
  "YOU ARE NEVER TOO OLD TO SET ANOTHER GOAL OR TO DREAM A NEW DREAM.",
  "SPREAD LOVE EVERYWHERE YOU GO. LET NO ONE EVER COME TO YOU WITHOUT LEAVING HAPPIER.",
  "BELIEVE YOU CAN AND YOU'RE HALFWAY THERE.",
  "LIFE IS WHAT HAPPENS WHEN YOU'RE BUSY MAKING OTHER PLANS.",
  "STAY HUNGRY, STAY FOOLISH.",
  "YOUR TIME IS LIMITED, SO DON'T WASTE IT LIVING SOMEONE ELSE'S LIFE.",
  "TURN YOUR WOUNDS INTO WISDOM.",
  "HAPPINESS DEPENDS UPON OURSELVES.",
  "SIMPLICITY IS THE ULTIMATE SOPHISTICATION.",
  "NOT ALL THOSE WHO WANDER ARE LOST.",
  "THE PURPOSE OF OUR LIVES IS TO BE HAPPY.",
  "GET BUSY LIVING OR GET BUSY DYING.",
  "YOU ONLY LIVE ONCE, BUT IF YOU DO IT RIGHT, ONCE IS ENOUGH.",
  "MANY OF LIFE'S FAILURES ARE PEOPLE WHO DID NOT REALIZE HOW CLOSE THEY WERE TO SUCCESS WHEN THEY GAVE UP.",
  "IF YOU WANT TO LIVE A HAPPY LIFE, TIE IT TO A GOAL, NOT TO PEOPLE OR THINGS.",
  "NEVER LET THE FEAR OF STRIKING OUT KEEP YOU FROM PLAYING THE GAME.",
  "MONEY AND SUCCESS DON'T CHANGE PEOPLE; THEY MERELY AMPLIFY WHAT IS ALREADY THERE.",
  "THE UNEXAMINED LIFE IS NOT WORTH LIVING.",
  "WHATEVER YOU ARE, BE A GOOD ONE.",
  "DREAM BIG AND DARE TO FAIL.",
  "COURAGE IS GRACE UNDER PRESSURE.",
  "IT ALWAYS SEEMS IMPOSSIBLE UNTIL IT IS DONE.",
  "KEEP YOUR FACE ALWAYS TOWARD THE SUNSHINE, AND SHADOWS WILL FALL BEHIND YOU.",
  "HAPPINESS IS NOT SOMETHING READY MADE. IT COMES FROM YOUR OWN ACTIONS.",
  "THE BEST WAY TO PREDICT THE FUTURE IS TO INVENT IT.",
  "WHAT WE THINK, WE BECOME.",
  "AN INVESTMENT IN KNOWLEDGE PAYS THE BEST INTEREST.",
  "WELL DONE IS BETTER THAN WELL SAID.",
  "THE ROOTS OF EDUCATION ARE BITTER, BUT THE FRUIT IS SWEET.",
  "PEACE BEGINS WITH A SMILE.",
  "NO ACT OF KINDNESS, NO MATTER HOW SMALL, IS EVER WASTED.",
  "WE MAY ENCOUNTER MANY DEFEATS BUT WE MUST NOT BE DEFEATED.",
  "IF YOU CANNOT DO GREAT THINGS, DO SMALL THINGS IN A GREAT WAY.",
  "TO SUCCEED IN LIFE, YOU NEED TWO THINGS: IGNORANCE AND CONFIDENCE.",
  "EVERY STRIKE BRINGS ME CLOSER TO THE NEXT HOME RUN.",
  "DEFINITENESS OF PURPOSE IS THE STARTING POINT OF ALL ACHIEVEMENT.",
  "LIFE ITSELF IS THE MOST WONDERFUL FAIRY TALE.",
  "A JOURNEY OF A THOUSAND MILES BEGINS WITH A SINGLE STEP.",
  "EDUCATION IS THE MOST POWERFUL WEAPON WHICH YOU CAN USE TO CHANGE THE WORLD.",
  "ACTION IS THE FOUNDATIONAL KEY TO ALL SUCCESS.",
  "TRY NOT TO BECOME A PERSON OF SUCCESS, BUT RATHER TRY TO BECOME A PERSON OF VALUE.",
  "THE SECRET OF GETTING AHEAD IS GETTING STARTED.",
  "DON'T COUNT THE DAYS, MAKE THE DAYS COUNT.",
  "CHAMPIONS KEEP PLAYING UNTIL THEY GET IT RIGHT.",
  "YOU MISS ONE HUNDRED PERCENT OF THE SHOTS YOU DON'T TAKE.",
  "IF OPPORTUNITY DOESN'T KNOCK, BUILD A DOOR.",
  "HARD WORK BEATS TALENT WHEN TALENT FAILS TO WORK HARD.",
  "THE DIFFERENCE BETWEEN ORDINARY AND EXTRAORDINARY IS THAT LITTLE EXTRA.",
  "BELIEVE AND ACT AS IF IT WERE IMPOSSIBLE TO FAIL.",
  "DO WHAT YOU CAN, WITH WHAT YOU HAVE, WHERE YOU ARE.",
  "LIGHT TOMORROW WITH TODAY.",
  "WHEREVER YOU GO, GO WITH ALL YOUR HEART.",
  "LIFE IS TEN PERCENT WHAT HAPPENS TO YOU AND NINETY PERCENT HOW YOU REACT TO IT.",
  "OPTIMISM IS THE FAITH THAT LEADS TO ACHIEVEMENT.",
  "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO.",
  "GREAT MINDS DISCUSS IDEAS; AVERAGE MINDS DISCUSS EVENTS; SMALL MINDS DISCUSS PEOPLE.",
  "IF YOU WANT TO LIFT YOURSELF UP, LIFT UP SOMEONE ELSE.",
  "BE YOURSELF; EVERYONE ELSE IS ALREADY TAKEN.",
  "TWO ROADS DIVERGED IN A WOOD, AND I TOOK THE ONE LESS TRAVELED BY.",
  "LIVE AS IF YOU WERE TO DIE TOMORROW. LEARN AS IF YOU WERE TO LIVE FOREVER.",
  "NO ONE CAN MAKE YOU FEEL INFERIOR WITHOUT YOUR CONSENT.",
  "WE ACCEPT THE LOVE WE THINK WE DESERVE.",
  "THERE IS NO CHARM EQUAL TO TENDERNESS OF HEART.",
  "ALL OUR DREAMS CAN COME TRUE, IF WE HAVE THE COURAGE TO PURSUE THEM.",
  "EVERY MOMENT IS A FRESH BEGINNING.",
  "NEVER REGRET ANYTHING THAT MADE YOU SMILE.",
  "DIE WITH MEMORIES, NOT DREAMS.",
  "ASPIRE TO INSPIRE BEFORE WE EXPIRE.",
  "EVERYTHING YOU CAN IMAGINE IS REAL.",
  "SIMPLICITY IS THE KEYNOTE OF ALL TRUE ELEGANCE.",
  "WHAT CONSUMES YOUR MIND CONTROLS YOUR LIFE.",
  "STRIVE NOT TO BE A SUCCESS, BUT RATHER TO BE OF VALUE.",
  "I WOULD RATHER DIE OF PASSION THAN OF BOREDOM.",
  "CHANGE YOUR THOUGHTS AND YOU CHANGE YOUR WORLD.",
  "NOTHING IS IMPOSSIBLE, THE WORD ITSELF SAYS I'M POSSIBLE.",
  "THE BAD NEWS IS TIME FLIES. THE GOOD NEWS IS YOU'RE THE PILOT.",
  "NEVER BEND YOUR HEAD. ALWAYS HOLD IT HIGH. LOOK THE WORLD STRAIGHT IN THE EYE.",
  "IT IS NEVER TOO LATE TO BE WHAT YOU MIGHT HAVE BEEN.",
  "PERFECTION IS NOT ATTAINABLE, BUT IF WE CHASE PERFECTION WE CAN CATCH EXCELLENCE.",
  "ENDEAVOR TO PERSIST, AS PERSEVERANCE UNLOCKS EVERY TREASURE OF THE SOUL.",
  "SILENCE IS A SOURCE OF GREAT STRENGTH.",
  "THE MIND IS EVERYTHING. WHAT YOU THINK YOU BECOME.",
  "KINDNESS IS A LANGUAGE WHICH THE DEAF CAN HEAR AND THE BLIND CAN SEE.",
  "A WARM SMILE IS THE UNIVERSAL LANGUAGE OF KINDNESS.",
  "THERE ARE NO SHORTCUTS TO ANY PLACE WORTH GOING.",
  "THE POWER OF IMAGINATION MAKES US INFINITE.",
  "CREATIVITY IS INTELLIGENCE HAVING FUN.",
  "DO ONE THING EVERY DAY THAT SCARES YOU.",
  "WISDOM BEGINS IN WONDER.",
  "PATIENCE IS A BITTER PLANT, BUT ITS FRUIT IS SWEET."
];

/**
 * Generate a target number of quotes for cryptogram puzzle books.
 * Cycles smoothly through the rich curated quotes pool, guaranteeing
 * clean authentic quotes without repeating identical back-to-back entries.
 */
export function getBulkCryptogramQuotes(targetCount: number, userQuotes: string[] = []): string[] {
  const cleanUser = userQuotes.map(q => q.trim()).filter(q => q.length > 5);
  const pool = cleanUser.length > 0 ? cleanUser : CRYPTOGRAM_QUOTES;
  const result: string[] = [];

  for (let i = 0; i < targetCount; i++) {
    const quote = pool[i % pool.length];
    result.push(quote);
  }

  return result;
}
