name: Build and deploy Node.js app to Azure Web App - ismamstudio

on:
  push:
    branches:
      - main
  workflow_dispatch:

# আপনার প্রজেক্ট ফোল্ডারের নাম (যেখানে package.json আছে)
env:
  APP_PATH: 'ai-book-generator'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: ./${{ env.APP_PATH }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./${{ env.APP_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73BB59128BF843228A7117ED89766FFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D66B85AAC4BF4E998C6EDBD338630AB3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0B1D99D8BD514BB0ADAEDCBC2B9D63FC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ismamstudio'
          slot-name: 'Production'
          package: .
